# Generated by Django 2.2 on 2024-03-29 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articals', '0002_alter_bloodrequestpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequestpost',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
